# Generated by Django 6.0.6 on 2026-07-13 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('dropdowns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(default='Test Certificate', max_length=50)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/')),
                ('html_layout', models.TextField(help_text='Full HTML with placeholders like {{client_name}}')),
                ('docx_template', models.FileField(help_text='Original DOCX with placeholders', upload_to='template_docx/')),
                ('header', models.TextField(blank=True)),
                ('footer', models.TextField(blank=True)),
                ('page_size', models.CharField(default='A4', max_length=20)),
                ('orientation', models.CharField(default='portrait', max_length=10)),
                ('margins', models.JSONField(default=dict)),
                ('logo_position', models.CharField(default='top-left', max_length=50)),
                ('signature_position', models.CharField(default='bottom-right', max_length=50)),
                ('qr_position', models.CharField(default='bottom-left', max_length=50)),
                ('barcode_position', models.CharField(default='bottom-center', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('textarea', 'Textarea'), ('image', 'Image'), ('signature', 'Signature'), ('formula', 'Formula'), ('auto_number', 'Auto Number'), ('auto_date', 'Auto Date'), ('hidden', 'Hidden'), ('readonly', 'Read Only'), ('file_upload', 'File Upload')], max_length=50)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('validation_rules', models.JSONField(default=dict)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('tooltip', models.CharField(blank=True, max_length=255)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('column_width', models.PositiveIntegerField(default=12)),
                ('order', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_printable', models.BooleanField(default=True)),
                ('is_searchable', models.BooleanField(default=False)),
                ('is_exportable', models.BooleanField(default=False)),
                ('formula_expression', models.TextField(blank=True, help_text='e.g., air_velocity = airflow / area')),
                ('dropdown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dropdowns.dropdownlist')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='templatesapp.template')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
