# Generated by Django 6.0.6 on 2026-07-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='validation_rules',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
