# Generated by Django 6.0.6 on 2026-07-13 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        ('templatesapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('generated', 'Generated'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='generated/pdf/')),
                ('generated_docx', models.FileField(blank=True, null=True, upload_to='generated/docx/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='generated/qr/')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='generated/barcode/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_data', models.JSONField(default=dict)),
                ('sent_email', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templatesapp.template')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='documents.document')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templatesapp.templatefield')),
            ],
            options={
                'unique_together': {('document', 'field')},
            },
        ),
    ]
